dataset: pwc_small
device: 0
lm:
  model:
    feat_shrink: 
    name: sentence-transformers/all-MiniLM-L6-v2
  train:
    att_dropout: 0.1
    batch_size: 9
    dropout: 0.3
    epochs: 20
    eval_patience: 1
    grad_acc_steps: 4
    lr: 0.0001
    use_gpt: False
    warmup_epochs: 0.6
    weight_decay: 0.0
runs: 5
seed: 0
data:
  name: pwc_small
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  device: 0
  split_index: [0.8, 0.15, 0.05]

out_dir: results
metric_best: acc
cfg_dest: ft-deberta.yaml
print: file
accelerator: auto
num_threads: 11

run:
  seed: 0
  num_threads: 11
  multiple_splits: None


train:
  mode: custom
  batch_size: 256
  eval_period: 1
  epochs: 10000
  device: 0
  auto_resume: False

model:
  device: 0
  type: ft-MLP-minilm
  hidden_channels: 128 #
  num_layers: 3 #
  dropout: 0.1