out_dir: results
metric_best: acc
cfg_dest: buddy.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None


train:
  mode: custom
  batch_size: 512 #
  eval_period: 1
  epochs: 100
  device: 0
  auto_resume: False
  final_eval: False
  finetune: False

model:
  type: BUDDY
  out_channels: 32
  in_channels: 1433
  hidden_channels: 256 #
  num_layers: 2 #
  label_dropout: 0.5 #
  feature_dropout: 0.1 #
  sign_dropout: 0.7 #
  use_zero_one: 0
  floor_sf: 0
  hll_p: 8
  minhash_num_perm: 128
  max_hash_hops: 2 #
  use_feature: True
  feature_prop: gcn
  propagate_embeddings: False
  sign_k: 0
  use_RA: False
  add_normed_features: False

num_threads: 11

wandb:
  use: True
  project: gtblueprint
  name_tag: buddy-arxiv-2023


data:
  name: arxiv_2023
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  1433
  device: 0
  split_index: [0.8, 0.15, 0.05]

optimizer:
  type: adam
  lr: 0.01 #
  weight_decay: 0.0005